spring:
  application:
    name: PRODUCT-SERVICE  
    
  datasource:
    url: jdbc:postgresql://localhost:5432/eth1
    username: postgres
    password: norcent
    
  data:
    rest:
        returnBodyOnCreate: true
        returnBodyOnupdate: true
        
        
info:
    app:
        name: Product Management Microservice
        groupId: com.igorsandler.demo1
        artifactId: domain-models-ms
        version: 1.0.0.1
        encoding: UTF-8
        java:
            source: 1.8.0_45
            target: 1.8.0_45        

eureka:
  client:
    healthcheck:
      enabled: true