spring:
  application:
    name: REGISTRY-SERVICE  

server:
  port: 8761

eureka:
  instance:
     hostname: eureka.peer1	
  client:
     registerWithEureka: true
     fetchRegistry: true
     serviceUrl: 
        defaultZone: http://eureka.peer2:8762/eureka   
    
          
