spring:
  application:
    name: ROUTER-SERVICE 
    

server:
  port: 9000

eureka:
  instance:
     hostname: eureka.peer1
  client:
     registerWithEureka: true
     fetchRegistry: true
     serviceUrl:
        defaultZone: http://eureka.peer2:8762/eureka,http://eureka.peer1:8761/eureka
          
ribbon:
    eureka:
        enabled: true     
    ConnectTimeout: 5000
    ReadTimeout: 5000
    ServerListRefreshInterval: 1000
    OkToRetryOnAllOperations: true
    MaxAutoRetriesNextServer: 3
    MaxAutoRetries: 3
         
