spring:
  application:
    name: REGISTRY-SERVICE  

server:
  port: 8762

eureka:
  instance:
     hostname: eureka.peer2	
     leaseRenewalIntervalInSeconds: 1
     leaseExpirationDurationInSeconds: 2
  server:
     enableSelfPreservation: true
  client:
     registerWithEureka: true
     fetchRegistry: true
     serviceUrl: 
        defaultZone: http://eureka.peer1:8761/eureka   
    
          
