spring:
  application:
    name: CUSTOMER-SERVICE  
    
  datasource:
    url: jdbc:postgresql://localhost:5432/eth1
    username: postgres
    password: norcent
    
  data:
    rest:
        returnBodyOnCreate: true
        returnBodyOnupdate: true
        
        
info:
    app:
        name: Customer Management Microservice
        groupId: @project.groupId@
        artifactId: @project.artifactId@
        version: @project.version@
        encoding: @project.build.sourceEncoding@
        java:
            source: @java.version@
            target: @java.version@        

eureka:
  client:
    healthcheck:
      enabled: true

    
#    jpa:
#       hibernate:
#          ddl-auto: create-drop
          
#server:
#    port: 9000
#    
#management:
#    port: 9001
#    address: 127.0.0.1   
    
    
          